// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="n_block_cbc_n_block_cbc,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1761-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.391000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=96,HLS_VERSION=2022_2}" *)

module n_block_cbc (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        encrypt_decrypt,
        message,
        key,
        ap_return
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   encrypt_decrypt;
input  [63:0] message;
input  [31:0] key;
output  [63:0] ap_return;

wire   [31:0] block_V_fu_56_p4;
wire   [0:0] key_V_fu_72_p0;
wire   [31:0] ret_V_fu_66_p2;
wire   [31:0] key_V_fu_72_p3;
wire   [31:0] block_V_1_fu_80_p1;
wire   [31:0] ret_V_1_fu_84_p2;
wire    ap_ce_reg;

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign ap_return = {{ret_V_fu_66_p2}, {ret_V_1_fu_84_p2}};

assign block_V_1_fu_80_p1 = message[31:0];

assign block_V_fu_56_p4 = {{message[63:32]}};

assign key_V_fu_72_p3 = ((key_V_fu_72_p0[0:0] == 1'b1) ? ret_V_fu_66_p2 : block_V_fu_56_p4);

assign ret_V_1_fu_84_p2 = (key_V_fu_72_p3 ^ block_V_1_fu_80_p1);

assign ret_V_fu_66_p2 = (key ^ block_V_fu_56_p4);

assign key_V_fu_72_p0 = encrypt_decrypt;

endmodule //n_block_cbc
