
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Jun  4 2025 20:43:07 CEST (Jun  4 2025 18:43:07 UTC)

// Verification Directory fv/pipeline 

module avg(rst_ni, clk_i, data_i, data_o);
  input rst_ni, clk_i;
  input [7:0] data_i;
  output [7:0] data_o;
  wire rst_ni, clk_i;
  wire [7:0] data_i;
  wire [7:0] data_o;
  wire [7:0] val1;
  wire [7:0] val2;
  wire [7:0] val3;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire csa_tree_ADD_TC_OP_1_groupi_n_0,
       csa_tree_ADD_TC_OP_1_groupi_n_1,
       csa_tree_ADD_TC_OP_1_groupi_n_2,
       csa_tree_ADD_TC_OP_1_groupi_n_3,
       csa_tree_ADD_TC_OP_1_groupi_n_4,
       csa_tree_ADD_TC_OP_1_groupi_n_5,
       csa_tree_ADD_TC_OP_1_groupi_n_6, csa_tree_ADD_TC_OP_1_groupi_n_7;
  wire csa_tree_ADD_TC_OP_1_groupi_n_8,
       csa_tree_ADD_TC_OP_1_groupi_n_9,
       csa_tree_ADD_TC_OP_1_groupi_n_10,
       csa_tree_ADD_TC_OP_1_groupi_n_11,
       csa_tree_ADD_TC_OP_1_groupi_n_12,
       csa_tree_ADD_TC_OP_1_groupi_n_13,
       csa_tree_ADD_TC_OP_1_groupi_n_14,
       csa_tree_ADD_TC_OP_1_groupi_n_15;
  wire csa_tree_ADD_TC_OP_1_groupi_n_16,
       csa_tree_ADD_TC_OP_1_groupi_n_17,
       csa_tree_ADD_TC_OP_1_groupi_n_18,
       csa_tree_ADD_TC_OP_1_groupi_n_19,
       csa_tree_ADD_TC_OP_1_groupi_n_20,
       csa_tree_ADD_TC_OP_1_groupi_n_21,
       csa_tree_ADD_TC_OP_1_groupi_n_22,
       csa_tree_ADD_TC_OP_1_groupi_n_23;
  wire csa_tree_ADD_TC_OP_1_groupi_n_24,
       csa_tree_ADD_TC_OP_1_groupi_n_25,
       csa_tree_ADD_TC_OP_1_groupi_n_26,
       csa_tree_ADD_TC_OP_1_groupi_n_27,
       csa_tree_ADD_TC_OP_1_groupi_n_28,
       csa_tree_ADD_TC_OP_1_groupi_n_29,
       csa_tree_ADD_TC_OP_1_groupi_n_31,
       csa_tree_ADD_TC_OP_1_groupi_n_32;
  wire csa_tree_ADD_TC_OP_1_groupi_n_33,
       csa_tree_ADD_TC_OP_1_groupi_n_34,
       csa_tree_ADD_TC_OP_1_groupi_n_35,
       csa_tree_ADD_TC_OP_1_groupi_n_36,
       csa_tree_ADD_TC_OP_1_groupi_n_37,
       csa_tree_ADD_TC_OP_1_groupi_n_38,
       csa_tree_ADD_TC_OP_1_groupi_n_39,
       csa_tree_ADD_TC_OP_1_groupi_n_40;
  wire csa_tree_ADD_TC_OP_1_groupi_n_41,
       csa_tree_ADD_TC_OP_1_groupi_n_42,
       csa_tree_ADD_TC_OP_1_groupi_n_43,
       csa_tree_ADD_TC_OP_1_groupi_n_44,
       csa_tree_ADD_TC_OP_1_groupi_n_45,
       csa_tree_ADD_TC_OP_1_groupi_n_46,
       csa_tree_ADD_TC_OP_1_groupi_n_47,
       csa_tree_ADD_TC_OP_1_groupi_n_48;
  wire csa_tree_ADD_TC_OP_1_groupi_n_49,
       csa_tree_ADD_TC_OP_1_groupi_n_50,
       csa_tree_ADD_TC_OP_1_groupi_n_51,
       csa_tree_ADD_TC_OP_1_groupi_n_52,
       csa_tree_ADD_TC_OP_1_groupi_n_53,
       csa_tree_ADD_TC_OP_1_groupi_n_55,
       csa_tree_ADD_TC_OP_1_groupi_n_56,
       csa_tree_ADD_TC_OP_1_groupi_n_57;
  wire csa_tree_ADD_TC_OP_1_groupi_n_58,
       csa_tree_ADD_TC_OP_1_groupi_n_59,
       csa_tree_ADD_TC_OP_1_groupi_n_60,
       csa_tree_ADD_TC_OP_1_groupi_n_61,
       csa_tree_ADD_TC_OP_1_groupi_n_64,
       csa_tree_ADD_TC_OP_1_groupi_n_66,
       csa_tree_ADD_TC_OP_1_groupi_n_68,
       csa_tree_ADD_TC_OP_1_groupi_n_70;
  wire csa_tree_ADD_TC_OP_1_groupi_n_72, n_0, n_1, n_2, n_3, n_4, n_5,
       n_6;
  wire n_7, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_143, n_144, n_145;
  DFFR_X1 \data_o_reg[0] (.RN (rst_ni), .CK (clk_i), .D (n_122), .Q
       (data_o[0]), .QN (UNCONNECTED));
  DFFR_X1 \data_o_reg[1] (.RN (rst_ni), .CK (clk_i), .D (n_121), .Q
       (data_o[1]), .QN (UNCONNECTED0));
  DFFR_X1 \data_o_reg[2] (.RN (rst_ni), .CK (clk_i), .D (n_120), .Q
       (data_o[2]), .QN (UNCONNECTED1));
  DFFR_X1 \data_o_reg[3] (.RN (rst_ni), .CK (clk_i), .D (n_113), .Q
       (data_o[3]), .QN (UNCONNECTED2));
  DFFR_X1 \data_o_reg[4] (.RN (rst_ni), .CK (clk_i), .D (n_97), .Q
       (data_o[4]), .QN (UNCONNECTED3));
  DFFR_X1 \data_o_reg[5] (.RN (rst_ni), .CK (clk_i), .D (n_71), .Q
       (data_o[5]), .QN (UNCONNECTED4));
  DFFR_X1 \data_o_reg[6] (.RN (rst_ni), .CK (clk_i), .D (n_77), .Q
       (data_o[6]), .QN (UNCONNECTED5));
  DFFR_X1 \data_o_reg[7] (.RN (rst_ni), .CK (clk_i), .D (n_143), .Q
       (data_o[7]), .QN (UNCONNECTED6));
  DFFR_X1 \val1_reg[0] (.RN (rst_ni), .CK (clk_i), .D (data_i[0]), .Q
       (val1[0]), .QN (UNCONNECTED7));
  DFFR_X1 \val1_reg[1] (.RN (rst_ni), .CK (clk_i), .D (data_i[1]), .Q
       (val1[1]), .QN (UNCONNECTED8));
  DFFR_X1 \val1_reg[2] (.RN (rst_ni), .CK (clk_i), .D (data_i[2]), .Q
       (val1[2]), .QN (UNCONNECTED9));
  DFFR_X1 \val1_reg[3] (.RN (rst_ni), .CK (clk_i), .D (data_i[3]), .Q
       (val1[3]), .QN (UNCONNECTED10));
  DFFR_X1 \val1_reg[4] (.RN (rst_ni), .CK (clk_i), .D (data_i[4]), .Q
       (val1[4]), .QN (UNCONNECTED11));
  DFFR_X1 \val1_reg[5] (.RN (rst_ni), .CK (clk_i), .D (data_i[5]), .Q
       (val1[5]), .QN (UNCONNECTED12));
  DFFR_X1 \val1_reg[6] (.RN (rst_ni), .CK (clk_i), .D (data_i[6]), .Q
       (val1[6]), .QN (UNCONNECTED13));
  DFFR_X1 \val1_reg[7] (.RN (rst_ni), .CK (clk_i), .D (data_i[7]), .Q
       (val1[7]), .QN (UNCONNECTED14));
  DFFR_X1 \val2_reg[0] (.RN (rst_ni), .CK (clk_i), .D (val1[0]), .Q
       (val2[0]), .QN (UNCONNECTED15));
  DFFR_X1 \val2_reg[1] (.RN (rst_ni), .CK (clk_i), .D (val1[1]), .Q
       (val2[1]), .QN (UNCONNECTED16));
  DFFR_X1 \val2_reg[2] (.RN (rst_ni), .CK (clk_i), .D (val1[2]), .Q
       (val2[2]), .QN (UNCONNECTED17));
  DFFR_X1 \val2_reg[3] (.RN (rst_ni), .CK (clk_i), .D (val1[3]), .Q
       (val2[3]), .QN (UNCONNECTED18));
  DFFR_X1 \val2_reg[4] (.RN (rst_ni), .CK (clk_i), .D (val1[4]), .Q
       (val2[4]), .QN (UNCONNECTED19));
  DFFR_X1 \val2_reg[5] (.RN (rst_ni), .CK (clk_i), .D (val1[5]), .Q
       (val2[5]), .QN (UNCONNECTED20));
  DFFR_X1 \val2_reg[6] (.RN (rst_ni), .CK (clk_i), .D (val1[6]), .Q
       (val2[6]), .QN (UNCONNECTED21));
  DFFR_X1 \val2_reg[7] (.RN (rst_ni), .CK (clk_i), .D (val1[7]), .Q
       (val2[7]), .QN (UNCONNECTED22));
  DFFR_X1 \val3_reg[0] (.RN (rst_ni), .CK (clk_i), .D (val2[0]), .Q
       (val3[0]), .QN (UNCONNECTED23));
  DFFR_X1 \val3_reg[1] (.RN (rst_ni), .CK (clk_i), .D (val2[1]), .Q
       (val3[1]), .QN (UNCONNECTED24));
  DFFR_X1 \val3_reg[2] (.RN (rst_ni), .CK (clk_i), .D (val2[2]), .Q
       (val3[2]), .QN (UNCONNECTED25));
  DFFR_X1 \val3_reg[3] (.RN (rst_ni), .CK (clk_i), .D (val2[3]), .Q
       (val3[3]), .QN (UNCONNECTED26));
  DFFR_X1 \val3_reg[4] (.RN (rst_ni), .CK (clk_i), .D (val2[4]), .Q
       (val3[4]), .QN (UNCONNECTED27));
  DFFR_X1 \val3_reg[5] (.RN (rst_ni), .CK (clk_i), .D (val2[5]), .Q
       (val3[5]), .QN (UNCONNECTED28));
  DFFR_X1 \val3_reg[6] (.RN (rst_ni), .CK (clk_i), .D (val2[6]), .Q
       (val3[6]), .QN (UNCONNECTED29));
  DFFR_X1 \val3_reg[7] (.RN (rst_ni), .CK (clk_i), .D (val2[7]), .Q
       (val3[7]), .QN (UNCONNECTED30));
  OAI221_X1 g179856__2398(.A (n_116), .B1 (n_117), .B2 (n_132), .C1
       (n_114), .C2 (n_145), .ZN (n_122));
  OAI221_X1 g179858__5107(.A (n_118), .B1 (n_100), .B2 (n_98), .C1
       (n_111), .C2 (n_132), .ZN (n_121));
  INV_X1 g179859(.A (n_119), .ZN (n_120));
  AOI211_X1 g179861__6260(.A (n_109), .B (n_115), .C1 (n_103), .C2
       (n_17), .ZN (n_119));
  AOI22_X1 g179862__4319(.A1 (n_112), .A2 (n_132), .B1 (n_96), .B2
       (n_15), .ZN (n_118));
  MUX2_X1 g179863__8428(.A (n_76), .B (n_108), .S (n_14), .Z (n_117));
  NAND2_X1 g179864__5526(.A1 (n_110), .A2 (n_132), .ZN (n_116));
  AOI21_X1 g179865__6783(.A (n_93), .B1 (n_102), .B2 (n_5), .ZN
       (n_115));
  AOI21_X1 g179866__3680(.A (n_110), .B1 (n_104), .B2 (n_132), .ZN
       (n_114));
  OAI221_X1 g179867__1617(.A (n_99), .B1 (n_91), .B2 (n_1), .C1 (n_89),
       .C2 (n_17), .ZN (n_113));
  NAND2_X1 g179868__2802(.A1 (n_102), .A2 (n_106), .ZN (n_112));
  NOR2_X1 g179869__1705(.A1 (n_103), .A2 (n_105), .ZN (n_111));
  OAI21_X1 g179870__5122(.A (n_101), .B1 (n_80), .B2 (n_14), .ZN
       (n_109));
  AOI21_X1 g179871__8246(.A (n_107), .B1 (n_72), .B2 (n_131), .ZN
       (n_108));
  OAI22_X1 g179872__7098(.A1 (n_94), .A2 (n_131), .B1 (n_93), .B2
       (n_4), .ZN (n_110));
  NOR2_X1 g179875__6131(.A1 (n_93), .A2 (n_131), .ZN (n_107));
  OAI21_X1 g179876__1881(.A (n_131), .B1 (n_85), .B2 (n_87), .ZN
       (n_106));
  AOI21_X1 g179877__5115(.A (n_131), .B1 (n_83), .B2 (n_88), .ZN
       (n_105));
  OAI21_X1 g179878__7482(.A (n_94), .B1 (n_86), .B2 (n_131), .ZN
       (n_104));
  OAI21_X1 g179879__4733(.A (n_131), .B1 (n_90), .B2 (n_82), .ZN
       (n_101));
  NOR3_X1 g179880__6161(.A1 (n_96), .A2 (n_130), .A3 (n_131), .ZN
       (n_100));
  AOI21_X1 g179881__9315(.A (n_82), .B1 (n_84), .B2 (n_26), .ZN (n_99));
  OAI221_X1 g179882__9945(.A (n_79), .B1 (n_75), .B2 (n_69), .C1
       (n_70), .C2 (n_60), .ZN (n_98));
  OAI22_X1 g179883__2883(.A1 (n_83), .A2 (n_1), .B1 (n_89), .B2
       (n_130), .ZN (n_103));
  AOI22_X1 g179884__2346(.A1 (n_85), .A2 (n_1), .B1 (n_82), .B2
       (n_130), .ZN (n_102));
  INV_X1 g179885(.A (n_95), .ZN (n_97));
  AOI21_X1 g179887__1666(.A (n_78), .B1 (n_69), .B2 (n_28), .ZN (n_95));
  NAND2_X1 g179888__7410(.A1 (n_89), .A2 (n_81), .ZN (n_96));
  AND3_X1 g179890__5477(.A1 (n_89), .A2 (n_61), .A3 (n_65), .ZN (n_91));
  AOI22_X1 g179891__2398(.A1 (n_72), .A2 (n_130), .B1 (n_73), .B2
       (n_1), .ZN (n_94));
  AOI21_X1 g179892__5107(.A (n_90), .B1 (n_73), .B2 (n_130), .ZN
       (n_93));
  OAI21_X1 g179894__6260(.A (n_130), .B1 (n_67), .B2 (n_55), .ZN
       (n_88));
  AOI21_X1 g179895__4319(.A (n_130), .B1 (n_62), .B2 (n_58), .ZN
       (n_87));
  AOI21_X1 g179896__8428(.A (n_72), .B1 (n_64), .B2 (n_130), .ZN
       (n_86));
  NOR2_X1 g179897__5526(.A1 (n_76), .A2 (n_130), .ZN (n_90));
  NAND2_X1 g179898__6783(.A1 (n_72), .A2 (n_124), .ZN (n_89));
  INV_X1 g179899(.A (n_83), .ZN (n_84));
  INV_X1 g179900(.A (n_82), .ZN (n_81));
  AOI211_X1 g179901__3680(.A (n_49), .B (n_73), .C1 (n_47), .C2 (n_18),
       .ZN (n_80));
  NAND3_X1 g179902__1617(.A1 (n_66), .A2 (n_62), .A3 (n_19), .ZN
       (n_79));
  OAI221_X1 g179903__2802(.A (n_61), .B1 (n_59), .B2 (n_0), .C1 (n_51),
       .C2 (n_26), .ZN (n_78));
  OAI221_X1 g179904__1705(.A (n_57), .B1 (n_32), .B2 (n_35), .C1
       (n_10), .C2 (n_42), .ZN (n_77));
  OAI22_X1 g179905__5122(.A1 (n_62), .A2 (n_0), .B1 (n_61), .B2
       (n_129), .ZN (n_85));
  AOI22_X1 g179906__8246(.A1 (n_68), .A2 (n_124), .B1 (n_67), .B2
       (n_0), .ZN (n_83));
  OAI22_X1 g179907__7098(.A1 (n_61), .A2 (n_0), .B1 (n_63), .B2
       (n_129), .ZN (n_82));
  NAND3_X1 g179908__6131(.A1 (n_63), .A2 (n_129), .A3 (n_130), .ZN
       (n_75));
  AOI21_X1 g179910__5115(.A (n_68), .B1 (n_50), .B2 (n_0), .ZN (n_76));
  OAI221_X1 g179911__7482(.A (n_36), .B1 (n_54), .B2 (n_2), .C1 (n_35),
       .C2 (n_24), .ZN (n_71));
  OAI211_X1 g179912__4733(.A (n_0), .B (n_131), .C1 (n_53), .C2 (n_2),
       .ZN (n_70));
  OAI22_X1 g179913__6161(.A1 (n_53), .A2 (n_129), .B1 (n_51), .B2
       (n_0), .ZN (n_73));
  OAI22_X1 g179914__9315(.A1 (n_52), .A2 (n_129), .B1 (n_53), .B2
       (n_0), .ZN (n_72));
  INV_X1 g179915(.A (n_67), .ZN (n_66));
  OAI21_X1 g179916__9945(.A (n_129), .B1 (n_45), .B2 (n_40), .ZN
       (n_65));
  OAI21_X1 g179917__2883(.A (n_52), .B1 (n_44), .B2 (n_129), .ZN
       (n_64));
  NOR2_X1 g179918__2346(.A1 (n_52), .A2 (n_2), .ZN (n_69));
  NOR2_X1 g179919__1666(.A1 (n_52), .A2 (n_0), .ZN (n_68));
  NOR2_X1 g179920__7410(.A1 (n_51), .A2 (n_2), .ZN (n_67));
  INV_X1 g179921(.A (n_61), .ZN (n_60));
  AOI211_X1 g179922__6417(.A (n_37), .B (n_50), .C1 (n_31), .C2 (n_16),
       .ZN (n_59));
  OAI21_X1 g179923__5477(.A (n_129), .B1 (n_47), .B2 (n_43), .ZN
       (n_58));
  NAND3_X1 g179924__2398(.A1 (n_22), .A2 (n_124), .A3 (n_48), .ZN
       (n_57));
  AOI22_X1 g179925__5107(.A1 (n_47), .A2 (n_128), .B1 (n_37), .B2
       (n_6), .ZN (n_63));
  AOI22_X1 g179926__6260(.A1 (n_45), .A2 (n_128), .B1 (n_47), .B2
       (n_6), .ZN (n_62));
  AOI22_X1 g179927__4319(.A1 (n_45), .A2 (n_6), .B1 (n_37), .B2
       (n_128), .ZN (n_61));
  NOR3_X1 g179929__8428(.A1 (n_46), .A2 (n_2), .A3 (n_129), .ZN (n_55));
  AOI22_X1 g179930__5526(.A1 (n_38), .A2 (n_41), .B1 (n_39), .B2
       (n_42), .ZN (n_54));
  INV_X1 g179931(.A (n_51), .ZN (n_50));
  OAI22_X1 g179932__6783(.A1 (n_36), .A2 (n_18), .B1 (n_27), .B2
       (n_20), .ZN (n_49));
  AOI22_X1 g179933__3680(.A1 (n_38), .A2 (n_128), .B1 (n_29), .B2
       (n_6), .ZN (n_53));
  AOI22_X1 g179934__1617(.A1 (n_38), .A2 (n_6), .B1 (n_39), .B2
       (n_128), .ZN (n_52));
  AOI22_X1 g179935__2802(.A1 (n_39), .A2 (n_6), .B1 (n_29), .B2
       (n_128), .ZN (n_51));
  AOI21_X1 g179936__1705(.A (n_29), .B1 (n_31), .B2 (n_128), .ZN
       (n_46));
  OR2_X1 g179937__5122(.A1 (n_42), .A2 (n_3), .ZN (n_48));
  AND2_X1 g179938__8246(.A1 (n_38), .A2 (n_2), .ZN (n_47));
  AOI21_X1 g179939__7098(.A (n_39), .B1 (n_30), .B2 (n_128), .ZN
       (n_44));
  AOI21_X1 g179940__6131(.A (n_128), .B1 (n_34), .B2 (n_25), .ZN
       (n_43));
  OAI22_X1 g179941__1881(.A1 (n_33), .A2 (n_124), .B1 (n_23), .B2
       (n_127), .ZN (n_45));
  NAND2_X1 g179942__5115(.A1 (n_6), .A2 (n_28), .ZN (n_41));
  NOR3_X1 g179943__7482(.A1 (n_30), .A2 (n_124), .A3 (n_128), .ZN
       (n_40));
  OR2_X1 g179944__4733(.A1 (n_6), .A2 (n_28), .ZN (n_42));
  INV_X1 g179945(.A (n_37), .ZN (n_36));
  OAI21_X1 g179946__6161(.A (n_33), .B1 (n_10), .B2 (n_127), .ZN
       (n_39));
  OAI22_X1 g179947__9315(.A1 (n_21), .A2 (n_127), .B1 (n_13), .B2
       (n_3), .ZN (n_38));
  OAI21_X1 g179948__9945(.A (n_34), .B1 (n_25), .B2 (n_127), .ZN
       (n_37));
  AND2_X1 g179949__2883(.A1 (n_25), .A2 (n_10), .ZN (n_32));
  AND2_X1 g179950__2346(.A1 (n_23), .A2 (n_3), .ZN (n_35));
  OR2_X1 g179951__1666(.A1 (n_23), .A2 (n_3), .ZN (n_34));
  NAND2_X1 g179952__7410(.A1 (n_22), .A2 (n_127), .ZN (n_33));
  AOI21_X1 g179953__6417(.A (n_22), .B1 (n_125), .B2 (n_3), .ZN (n_27));
  OAI21_X1 g179954__5477(.A (n_13), .B1 (n_11), .B2 (n_127), .ZN
       (n_31));
  AOI21_X1 g179955__2398(.A (n_22), .B1 (n_7), .B2 (n_127), .ZN (n_30));
  OAI22_X1 g179956__5107(.A1 (n_13), .A2 (n_127), .B1 (n_10), .B2
       (n_3), .ZN (n_29));
  OR2_X1 g179957__6260(.A1 (n_0), .A2 (n_26), .ZN (n_28));
  NAND2_X1 g179958__4319(.A1 (n_16), .A2 (n_13), .ZN (n_24));
  NAND2_X1 g179959__8428(.A1 (n_15), .A2 (n_132), .ZN (n_26));
  NAND2_X1 g179960__5526(.A1 (n_12), .A2 (n_2), .ZN (n_25));
  INV_X1 g179961(.A (n_22), .ZN (n_21));
  NAND2_X1 g179962__6783(.A1 (n_16), .A2 (n_0), .ZN (n_20));
  OAI22_X1 g179963__3680(.A1 (n_129), .A2 (n_1), .B1 (n_0), .B2 (n_4),
       .ZN (n_19));
  NAND2_X1 g179964__1617(.A1 (n_11), .A2 (n_2), .ZN (n_23));
  NOR2_X1 g179965__2802(.A1 (n_11), .A2 (n_12), .ZN (n_22));
  INV_X1 g179981(.A (n_15), .ZN (n_14));
  INV_X1 g179982(.A (n_13), .ZN (n_12));
  INV_X1 g179983(.A (n_11), .ZN (n_10));
  NAND2_X1 g179990__1705(.A1 (n_6), .A2 (n_129), .ZN (n_18));
  NAND2_X1 g179994__5122(.A1 (n_131), .A2 (n_132), .ZN (n_17));
  NOR2_X1 g179996__8246(.A1 (n_124), .A2 (n_6), .ZN (n_16));
  NOR2_X1 g179997__7098(.A1 (n_1), .A2 (n_4), .ZN (n_15));
  NAND2_X1 g179998__6131(.A1 (n_7), .A2 (n_126), .ZN (n_13));
  NOR2_X1 g179999__1881(.A1 (n_7), .A2 (n_126), .ZN (n_11));
  INV_X1 g180001(.A (n_125), .ZN (n_7));
  INV_X1 g180002(.A (n_128), .ZN (n_6));
  INV_X1 g180003(.A (n_132), .ZN (n_5));
  INV_X1 g180004(.A (n_131), .ZN (n_4));
  INV_X1 g180005(.A (n_127), .ZN (n_3));
  INV_X1 g180006(.A (n_124), .ZN (n_2));
  INV_X1 g180007(.A (n_130), .ZN (n_1));
  INV_X1 g180008(.A (n_129), .ZN (n_0));
  AOI21_X1 csa_tree_ADD_TC_OP_1_groupi_g805__5115(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_35), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_72), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_33), .ZN (n_124));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g806__7482(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_72), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_38), .ZN (n_125));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g807__4733(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_50), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_70), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_44), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_72));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g808__6161(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_70), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_55), .ZN (n_126));
  AOI21_X1 csa_tree_ADD_TC_OP_1_groupi_g809__9315(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_40), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_68), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_46), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_70));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g810__9945(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_68), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_60), .ZN (n_127));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g811__2883(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_53), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_66), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_42), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_68));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g812__2346(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_66), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_59), .ZN (n_128));
  AOI21_X1 csa_tree_ADD_TC_OP_1_groupi_g813__1666(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_39), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_64), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_49), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_66));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g814__7410(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_64), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_58), .ZN (n_129));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g815__6417(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_48), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_61), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_45), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_64));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g816__5477(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_61), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_56), .ZN (n_130));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g817__2398(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_57), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_41), .ZN (n_131));
  AOI21_X1 csa_tree_ADD_TC_OP_1_groupi_g818__5107(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_37), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_41), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_43), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_61));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g819__6260(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_46), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_26), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_19), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_60));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g820__4319(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_52), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_42), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_59));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g821__8428(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_49), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_31), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_17), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_58));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g822__5526(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_43), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_28), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_1), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_57));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g823__6783(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_47), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_45), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_56));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g824__3680(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_51), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_44), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_55));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g825__1617(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_36), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_18), .ZN (n_132));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g826(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_52), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_53));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g827(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_50), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_51));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g828(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_47), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_48));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g829__2802(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_27), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_21), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_52));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g830__1705(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_32), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_20), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_50));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g831__5122(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_31), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_17), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_49));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g832__8246(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_29), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_22), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_47));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g833__7098(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_26), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_19), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_46));
  AND2_X1 csa_tree_ADD_TC_OP_1_groupi_g834__6131(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_29), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_22), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_45));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g835__1881(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_32), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_20), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_44));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g836__5115(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_28), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_1), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_43));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g837__7482(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_26), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_19), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_40));
  AND2_X1 csa_tree_ADD_TC_OP_1_groupi_g838__4733(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_27), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_21), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_42));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g839__6161(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_31), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_17), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_39));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g840__9315(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_33), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_34), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_38));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g841__9945(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_28), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_1), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_37));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g842__2883(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_24), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_23), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_18), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_41));
  AOI21_X1 csa_tree_ADD_TC_OP_1_groupi_g843__2346(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_23), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_9), .B2 (val2[1]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_36));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g844(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_34), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_35));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g845__1666(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_25), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_5), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_34));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g846__7410(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_25), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_5), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_33));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g847__6417(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_25), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_12), .B2 (val1[7]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_32));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g848__5477(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_14), .B (val1[4]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_31));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g850__5107(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_11), .B (val1[3]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_29));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g851__6260(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_10), .B (val1[2]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_28));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g852__4319(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_8), .B (val1[5]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_27));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g853__8428(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_15), .B (val1[6]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_26));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g854__5526(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_12), .A2 (val1[7]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_25));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g855__6783(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_9), .A2 (val2[1]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_24));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g856__3680(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_9), .A2 (val2[1]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_23));
  AOI22_X1 csa_tree_ADD_TC_OP_1_groupi_g857__1617(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_2), .A2 (val2[2]), .B1 (val1[2]),
       .B2 (val3[2]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_22));
  AOI22_X1 csa_tree_ADD_TC_OP_1_groupi_g858__2802(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_3), .A2 (val2[4]), .B1 (val1[4]),
       .B2 (val3[4]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_21));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g859__1705(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_16), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_4), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_20));
  AOI22_X1 csa_tree_ADD_TC_OP_1_groupi_g860__5122(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_6), .A2 (val2[5]), .B1 (val1[5]),
       .B2 (val3[5]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_19));
  AOI22_X1 csa_tree_ADD_TC_OP_1_groupi_g861__8246(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_0), .A2 (val2[0]), .B1 (val3[0]),
       .B2 (val1[0]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_18));
  AOI22_X1 csa_tree_ADD_TC_OP_1_groupi_g862__7098(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_7), .A2 (val2[3]), .B1 (val1[3]),
       .B2 (val3[3]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_17));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g863__6131(.A (val2[6]), .B1
       (val1[6]), .B2 (val3[6]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_16));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g864__1881(.A (val2[6]), .B
       (val3[6]), .Z (csa_tree_ADD_TC_OP_1_groupi_n_15));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g865__5115(.A (val2[4]), .B
       (val3[4]), .Z (csa_tree_ADD_TC_OP_1_groupi_n_14));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g866__7482(.A (val2[0]), .B
       (val1[0]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_13));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g867__4733(.A (val2[7]), .B
       (val3[7]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_12));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g868__6161(.A (val2[3]), .B
       (val3[3]), .Z (csa_tree_ADD_TC_OP_1_groupi_n_11));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g869__9315(.A (val2[2]), .B
       (val3[2]), .Z (csa_tree_ADD_TC_OP_1_groupi_n_10));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g870__9945(.A (val1[1]), .B
       (val3[1]), .Z (csa_tree_ADD_TC_OP_1_groupi_n_9));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g871__2883(.A (val2[5]), .B
       (val3[5]), .Z (csa_tree_ADD_TC_OP_1_groupi_n_8));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g872__2346(.A1 (val1[3]), .A2
       (val3[3]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_7));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g873__1666(.A1 (val1[5]), .A2
       (val3[5]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_6));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g874__7410(.A1 (val2[7]), .A2
       (val3[7]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_5));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g875__6417(.A1 (val1[6]), .A2
       (val3[6]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_4));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g876__5477(.A1 (val1[4]), .A2
       (val3[4]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_3));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g877__2398(.A1 (val1[2]), .A2
       (val3[2]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_2));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g878__5107(.A1 (val1[1]), .A2
       (val3[1]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_1));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g879__6260(.A1 (val1[0]), .A2
       (val3[0]), .ZN (csa_tree_ADD_TC_OP_1_groupi_n_0));
  NOR2_X1 g2(.A1 (n_144), .A2 (n_2), .ZN (n_143));
  NOR2_X1 g180009(.A1 (n_21), .A2 (n_48), .ZN (n_144));
  XOR2_X1 g180010(.A (csa_tree_ADD_TC_OP_1_groupi_n_13), .B (val3[0]),
       .Z (n_145));
endmodule

module seg_display(clk_i, rst_ni, data_i, fourteen_seg_out);
  input clk_i, rst_ni;
  input [7:0] data_i;
  output [14:0] fourteen_seg_out;
  wire clk_i, rst_ni;
  wire [7:0] data_i;
  wire [14:0] fourteen_seg_out;
  wire [2:0] next_state;
  wire [2:0] current_state;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_35, n_36, n_37, n_42;
  DFFR_X1 \fourteen_seg_out_reg[3] (.RN (rst_ni), .CK (clk_i), .D
       (n_37), .Q (fourteen_seg_out[12]), .QN (UNCONNECTED31));
  DFFR_X1 \fourteen_seg_out_reg[11] (.RN (rst_ni), .CK (clk_i), .D
       (n_36), .Q (fourteen_seg_out[11]), .QN (UNCONNECTED32));
  DFFS_X1 \fourteen_seg_out_reg[7] (.SN (rst_ni), .CK (clk_i), .D
       (n_35), .Q (fourteen_seg_out[8]), .QN (UNCONNECTED33));
  NOR2_X1 g1464__4319(.A1 (n_35), .A2 (next_state[2]), .ZN (n_37));
  NOR2_X1 g1465__8428(.A1 (n_35), .A2 (n_0), .ZN (n_36));
  NOR3_X1 g1466__5526(.A1 (next_state[0]), .A2 (n_0), .A3
       (next_state[2]), .ZN (n_35));
  DFFS_X1 \fourteen_seg_out_reg[14] (.SN (rst_ni), .CK (clk_i), .D
       (n_42), .Q (fourteen_seg_out[14]), .QN (UNCONNECTED34));
  INV_X1 g1468(.A (n_0), .ZN (n_42));
  NOR2_X1 g1469__6783(.A1 (n_33), .A2 (n_23), .ZN (n_0));
  OAI221_X1 g1470__3680(.A (n_32), .B1 (n_27), .B2 (n_19), .C1 (n_11),
       .C2 (n_24), .ZN (next_state[0]));
  DFFR_X1 \fourteen_seg_out_reg[0] (.RN (rst_ni), .CK (clk_i), .D
       (n_31), .Q (fourteen_seg_out[0]), .QN (UNCONNECTED35));
  NOR3_X1 g1472__1617(.A1 (n_30), .A2 (n_7), .A3 (n_5), .ZN (n_33));
  OAI22_X1 g1473__2802(.A1 (n_29), .A2 (n_22), .B1 (n_28), .B2 (n_20),
       .ZN (next_state[2]));
  INV_X1 g1474(.A (n_31), .ZN (n_32));
  OAI22_X1 g1475__1705(.A1 (n_26), .A2 (data_i[7]), .B1 (n_11), .B2
       (n_18), .ZN (n_31));
  INV_X1 g1476(.A (n_29), .ZN (n_30));
  NAND2_X1 g1477__5122(.A1 (n_10), .A2 (n_24), .ZN (n_29));
  NOR2_X1 g1478__8246(.A1 (n_25), .A2 (n_7), .ZN (n_28));
  AOI21_X1 g1479__7098(.A (n_25), .B1 (n_7), .B2 (n_23), .ZN (n_27));
  OAI21_X1 g1480__6131(.A (n_7), .B1 (n_21), .B2 (data_i[6]), .ZN
       (n_26));
  AND2_X1 g1481__1881(.A1 (n_5), .A2 (n_23), .ZN (n_25));
  OAI211_X1 g1482__5115(.A (n_23), .B (n_20), .C1 (n_13), .C2
       (data_i[4]), .ZN (n_24));
  INV_X1 g1483(.A (n_23), .ZN (n_22));
  OAI21_X1 g1484__7482(.A (n_2), .B1 (n_14), .B2 (data_i[6]), .ZN
       (n_23));
  AND2_X1 g1485__4733(.A1 (n_16), .A2 (data_i[4]), .ZN (n_21));
  INV_X1 g1486(.A (n_20), .ZN (n_19));
  AOI21_X1 g1487__6161(.A (n_17), .B1 (n_9), .B2 (data_i[7]), .ZN
       (n_18));
  AOI21_X1 g1488__9315(.A (n_15), .B1 (n_6), .B2 (data_i[7]), .ZN
       (n_20));
  AOI211_X1 g1489__9945(.A (data_i[5]), .B (n_12), .C1 (data_i[0]), .C2
       (data_i[1]), .ZN (n_17));
  OAI21_X1 g1490__2883(.A (n_13), .B1 (n_8), .B2 (n_1), .ZN (n_16));
  NOR3_X1 g1491__2346(.A1 (n_12), .A2 (data_i[0]), .A3 (data_i[1]), .ZN
       (n_15));
  AOI21_X1 g1492__1666(.A (n_1), .B1 (n_8), .B2 (n_3), .ZN (n_14));
  NAND4_X1 g1493__7410(.A1 (data_i[3]), .A2 (data_i[5]), .A3
       (data_i[0]), .A4 (data_i[2]), .ZN (n_13));
  INV_X1 g1494(.A (n_10), .ZN (n_11));
  OAI21_X1 g1495__6417(.A (data_i[6]), .B1 (data_i[5]), .B2
       (data_i[4]), .ZN (n_9));
  OR3_X1 g1496__5477(.A1 (n_2), .A2 (data_i[3]), .A3 (data_i[2]), .ZN
       (n_12));
  NOR3_X1 g1497__2398(.A1 (fourteen_seg_out[13]), .A2
       (current_state[1]), .A3 (current_state[0]), .ZN (n_10));
  NAND3_X1 g1498__5107(.A1 (data_i[5]), .A2 (data_i[4]), .A3
       (data_i[6]), .ZN (n_6));
  NAND3_X1 g1499__6260(.A1 (data_i[3]), .A2 (data_i[1]), .A3
       (data_i[2]), .ZN (n_8));
  NOR3_X1 g1500__4319(.A1 (n_4), .A2 (current_state[2]), .A3
       (current_state[0]), .ZN (n_7));
  NOR2_X1 g1501__8428(.A1 (current_state[2]), .A2 (current_state[1]),
       .ZN (n_5));
  INV_X1 g1504(.A (data_i[4]), .ZN (n_3));
  INV_X1 g1505(.A (data_i[7]), .ZN (n_2));
  INV_X1 g1506(.A (data_i[5]), .ZN (n_1));
  DFFR_X1 \current_state_reg[1] (.RN (rst_ni), .CK (clk_i), .D (n_0),
       .Q (current_state[1]), .QN (n_4));
  DFFR_X1 \current_state_reg[0] (.RN (rst_ni), .CK (clk_i), .D
       (next_state[0]), .Q (current_state[0]), .QN (UNCONNECTED36));
  DFFR_X1 \current_state_reg[2] (.RN (rst_ni), .CK (clk_i), .D
       (next_state[2]), .Q (current_state[2]), .QN
       (fourteen_seg_out[13]));
endmodule

module pipeline(rst_ni, clock_slow, clock_fast, temperature,
     fourteen_seg_o);
  input rst_ni, clock_slow, clock_fast;
  input [7:0] temperature;
  output [14:0] fourteen_seg_o;
  wire rst_ni, clock_slow, clock_fast;
  wire [7:0] temperature;
  wire [14:0] fourteen_seg_o;
  wire [7:0] avg_out;
  wire [7:0] cdc_out;
  wire [7:0] \gen_cdc.i_cdc_ff_2 ;
  wire [7:0] \gen_cdc.i_cdc_ff_1 ;
  wire UNCONNECTED37, UNCONNECTED38, UNCONNECTED39, UNCONNECTED40,
       UNCONNECTED41, UNCONNECTED42, UNCONNECTED43, UNCONNECTED44;
  wire UNCONNECTED45, UNCONNECTED46, UNCONNECTED47, UNCONNECTED48,
       UNCONNECTED49, UNCONNECTED50, UNCONNECTED51, UNCONNECTED52;
  wire UNCONNECTED53, UNCONNECTED54, UNCONNECTED55, UNCONNECTED56,
       UNCONNECTED57, UNCONNECTED58, UNCONNECTED59, UNCONNECTED60;
  wire UNCONNECTED61, UNCONNECTED62, UNCONNECTED63, UNCONNECTED64,
       UNCONNECTED65, UNCONNECTED66, UNCONNECTED67, UNCONNECTED68;
  wire UNCONNECTED69;
  assign fourteen_seg_o[1] = fourteen_seg_o[13];
  assign fourteen_seg_o[2] = 1'b0;
  assign fourteen_seg_o[3] = fourteen_seg_o[12];
  assign fourteen_seg_o[4] = 1'b0;
  assign fourteen_seg_o[5] = 1'b0;
  assign fourteen_seg_o[6] = 1'b0;
  assign fourteen_seg_o[7] = fourteen_seg_o[8];
  assign fourteen_seg_o[9] = 1'b1;
  assign fourteen_seg_o[10] = 1'b1;
  avg avg(.rst_ni (rst_ni), .clk_i (clock_fast), .data_i (temperature),
       .data_o (avg_out));
  seg_display i_seg_display(.clk_i (clock_slow), .rst_ni (rst_ni),
       .data_i (cdc_out), .fourteen_seg_out ({fourteen_seg_o[14:11],
       UNCONNECTED45, UNCONNECTED44, fourteen_seg_o[8], UNCONNECTED43,
       UNCONNECTED42, UNCONNECTED41, UNCONNECTED40, UNCONNECTED39,
       UNCONNECTED38, UNCONNECTED37, fourteen_seg_o[0]}));
  DFFR_X1 \gen_cdc.i_cdc_ff_3_reg[5] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_2 [5]), .Q (cdc_out[5]), .QN
       (UNCONNECTED46));
  DFFR_X1 \gen_cdc.i_cdc_ff_3_reg[6] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_2 [6]), .Q (cdc_out[6]), .QN
       (UNCONNECTED47));
  DFFR_X1 \gen_cdc.i_cdc_ff_3_reg[4] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_2 [4]), .Q (cdc_out[4]), .QN
       (UNCONNECTED48));
  DFFR_X1 \gen_cdc.i_cdc_ff_3_reg[1] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_2 [1]), .Q (cdc_out[1]), .QN
       (UNCONNECTED49));
  DFFR_X1 \gen_cdc.i_cdc_ff_3_reg[3] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_2 [3]), .Q (cdc_out[3]), .QN
       (UNCONNECTED50));
  DFFR_X1 \gen_cdc.i_cdc_ff_3_reg[7] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_2 [7]), .Q (cdc_out[7]), .QN
       (UNCONNECTED51));
  DFFR_X1 \gen_cdc.i_cdc_ff_3_reg[0] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_2 [0]), .Q (cdc_out[0]), .QN
       (UNCONNECTED52));
  DFFR_X1 \gen_cdc.i_cdc_ff_3_reg[2] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_2 [2]), .Q (cdc_out[2]), .QN
       (UNCONNECTED53));
  DFFR_X1 \gen_cdc.i_cdc_ff_2_reg[2] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_1 [2]), .Q (\gen_cdc.i_cdc_ff_2 [2]), .QN
       (UNCONNECTED54));
  DFFR_X1 \gen_cdc.i_cdc_ff_2_reg[0] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_1 [0]), .Q (\gen_cdc.i_cdc_ff_2 [0]), .QN
       (UNCONNECTED55));
  DFFR_X1 \gen_cdc.i_cdc_ff_2_reg[1] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_1 [1]), .Q (\gen_cdc.i_cdc_ff_2 [1]), .QN
       (UNCONNECTED56));
  DFFR_X1 \gen_cdc.i_cdc_ff_2_reg[3] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_1 [3]), .Q (\gen_cdc.i_cdc_ff_2 [3]), .QN
       (UNCONNECTED57));
  DFFR_X1 \gen_cdc.i_cdc_ff_2_reg[4] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_1 [4]), .Q (\gen_cdc.i_cdc_ff_2 [4]), .QN
       (UNCONNECTED58));
  DFFR_X1 \gen_cdc.i_cdc_ff_2_reg[5] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_1 [5]), .Q (\gen_cdc.i_cdc_ff_2 [5]), .QN
       (UNCONNECTED59));
  DFFR_X1 \gen_cdc.i_cdc_ff_2_reg[6] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_1 [6]), .Q (\gen_cdc.i_cdc_ff_2 [6]), .QN
       (UNCONNECTED60));
  DFFR_X1 \gen_cdc.i_cdc_ff_2_reg[7] (.RN (rst_ni), .CK (clock_slow),
       .D (\gen_cdc.i_cdc_ff_1 [7]), .Q (\gen_cdc.i_cdc_ff_2 [7]), .QN
       (UNCONNECTED61));
  DFFR_X1 \gen_cdc.i_cdc_ff_1_reg[5] (.RN (rst_ni), .CK (clock_fast),
       .D (avg_out[5]), .Q (\gen_cdc.i_cdc_ff_1 [5]), .QN
       (UNCONNECTED62));
  DFFR_X1 \gen_cdc.i_cdc_ff_1_reg[6] (.RN (rst_ni), .CK (clock_fast),
       .D (avg_out[6]), .Q (\gen_cdc.i_cdc_ff_1 [6]), .QN
       (UNCONNECTED63));
  DFFR_X1 \gen_cdc.i_cdc_ff_1_reg[1] (.RN (rst_ni), .CK (clock_fast),
       .D (avg_out[1]), .Q (\gen_cdc.i_cdc_ff_1 [1]), .QN
       (UNCONNECTED64));
  DFFR_X1 \gen_cdc.i_cdc_ff_1_reg[2] (.RN (rst_ni), .CK (clock_fast),
       .D (avg_out[2]), .Q (\gen_cdc.i_cdc_ff_1 [2]), .QN
       (UNCONNECTED65));
  DFFR_X1 \gen_cdc.i_cdc_ff_1_reg[7] (.RN (rst_ni), .CK (clock_fast),
       .D (avg_out[7]), .Q (\gen_cdc.i_cdc_ff_1 [7]), .QN
       (UNCONNECTED66));
  DFFR_X1 \gen_cdc.i_cdc_ff_1_reg[4] (.RN (rst_ni), .CK (clock_fast),
       .D (avg_out[4]), .Q (\gen_cdc.i_cdc_ff_1 [4]), .QN
       (UNCONNECTED67));
  DFFR_X1 \gen_cdc.i_cdc_ff_1_reg[0] (.RN (rst_ni), .CK (clock_fast),
       .D (avg_out[0]), .Q (\gen_cdc.i_cdc_ff_1 [0]), .QN
       (UNCONNECTED68));
  DFFR_X1 \gen_cdc.i_cdc_ff_1_reg[3] (.RN (rst_ni), .CK (clock_fast),
       .D (avg_out[3]), .Q (\gen_cdc.i_cdc_ff_1 [3]), .QN
       (UNCONNECTED69));
endmodule

// GENUS UID 4c533407f939851cb844a6d0dba1b3d2
